# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14H4HoSev0kFJT7xvBT3ZuS8bYkS5IfQE
"""

#Valery Montes
#01240372023

import csv
import random
from google.colab import files
import ipywidgets as widgets
from IPython.display import display, clear_output

registroForestal = []

nombreComun = widgets.Text(description="Nombre:")
municipio = widgets.Text(description="Municipio:")
brigada = widgets.Text(description="Brigada:")
lote = widgets.Text(description="Lote:")

#Tipo de especie
tipoEspecie = widgets.Dropdown(
    options=[("Pájaro","Pájaro"),("Flor","Flor")],
    description="Especie:")

#Tipo de registro
tipoRegistro = widgets.Dropdown(options=[("Ave pequeña","Ave pequeña"),("Ave mediana","Ave mediana"),("Ave grande","Ave grande"),

      ("Silvestre","Silvestre"),("Medicinal","Medicinal"),("Ornamental","Ornamental")],description="Tipo:")

#Opciones del sistema
opciones = widgets.Dropdown(options=[("Agregar",1),("Eliminar",2),("Imprimir",3),("Descargar",4)],description='Opción:')

#Opciones de descarga
tipoDescarga = widgets.Dropdown(options=[("Por lotes","lotes"),("Por especies","especies")],description="Descargar:")

boton = widgets.Button(description="Ejecutar")
salida = widgets.Output()

def ejecutar(b):

    with salida:
        clear_output()
        opcion = opciones.value
        if opcion == 1:
            nombreComunData = nombreComun.value
            municipioData = municipio.value
            brigadaData = brigada.value
            loteData = lote.value
            tipoEspecieData = tipoEspecie.value
            tipoRegistroData = tipoRegistro.value

            #ID generado automáticamente
            idRegistro = random.randint(1000,9999)

            registroAgregar = [idRegistro,tipoEspecieData,nombreComunData,tipoRegistroData,municipioData,brigadaData,loteData]
            registroForestal.append(registroAgregar)
            print(f"Registro {idRegistro} agregado correctamente")

        elif opcion == 2:
            try:
                indiceEliminar = int(nombreComun.value.strip()) - 1
                if 0 <= indiceEliminar < len(registroForestal):
                    registroForestal.pop(indiceEliminar)
                    print(f"Registro {indiceEliminar + 1} eliminado")
                else:
                    print("Número no válido")
            except:
                print("Ingresa el número del registro en el campo Nombre")

        elif opcion == 3:
            if registroForestal:
                for datos in registroForestal:
                    print(f"\nID: {datos[0]}")
                    print(f"Especie: {datos[1]}")
                    print(f"Nombre común: {datos[2]}")
                    print(f"Tipo: {datos[3]}")
                    print(f"Municipio: {datos[4]}")
                    print(f"Brigada: {datos[5]}")
                    print(f"Lote: {datos[6]}")
            else:
                print("No hay registros guardados")

        elif opcion == 4:
            if tipoDescarga.value == "lotes":
                lotesRegistrados = []
                for datos in registroForestal:
                    if datos[6] not in lotesRegistrados:
                        lotesRegistrados.append(datos[6])
                        with open(f"lote_{datos[6]}.csv","w",newline="") as archivo:
                            writer = csv.writer(archivo)
                            writer.writerow(["ID","Especie","Nombre común","Tipo","Municipio","Brigada","Lote"])
                            for fila in registroForestal:
                                if fila[6] == datos[6]:
                                    writer.writerow(fila)
                        files.download(f"lote_{datos[6]}.csv")

            elif tipoDescarga.value == "especies":
                especiesRegistradas = []
                for datos in registroForestal:
                    if datos[1] not in especiesRegistradas:
                        especiesRegistradas.append(datos[1])
                        with open(f"{datos[1]}.csv","w",newline="") as archivo:
                            writer = csv.writer(archivo)
                            writer.writerow(["ID","Especie","Nombre común","Tipo","Municipio","Brigada","Lote"])
                            for fila in registroForestal:
                                if fila[1] == datos[1]:
                                    writer.writerow(fila)
                        files.download(f"{datos[1]}.csv")

#Evento del botón
boton.on_click(ejecutar)

#Mostrar interfaz
display(nombreComun,municipio,brigada,lote,tipoEspecie,tipoRegistro,tipoDescarga,opciones,boton,salida)