# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14H4HoSev0kFJT7xvBT3ZuS8bYkS5IfQE
"""

#Valery Montes
#01240372023

if "registroForestal" not in dir():
    registroForestal    = []
    idsEspecies         = {}
    contadorEspecies=1
print(f"Estado cargado — {len(registroForestal)} registro(s) en memoria.")

import csv
from google.colab import files
import ipywidgets as widgets
from IPython.display import display, clear_output

if "registroForestal" not in dir():
    raise RuntimeError("Ejecuta primero la Celda 1 para inicializar el estado.")

layoutMitad = widgets.Layout(width="48%", margin="6px 1%")
layoutCompleto = widgets.Layout(width="98%", margin="6px 1%")
layoutTercio = widgets.Layout(width="31%", margin="6px 1%")

styleLabel = {"description_width": "initial"}

#Brigadas
tituloBrigada = widgets.HTML(
    "<h3 style='color:GREY;'>INFORMACIÓN DE LA BRIGADA</h3>")

nombreBrigada = widgets.Text(
    description="Nombre de brigada",
    placeholder="Ej: Brigada Amazonas 01",
    layout=layoutMitad,
    style=styleLabel)

responsableBrigada = widgets.Text(
    description="Lider",
    placeholder="Nombre del lider de brigada",
    layout=layoutMitad,
    style=styleLabel)

colaboradorUno = widgets.Text(
    description="Colaborador 1",
    layout=layoutMitad,
    style=styleLabel)

colaboradorDos = widgets.Text(
    description="Colaborador 2",
    layout=layoutMitad,
    style=styleLabel)

colaboradorTres = widgets.Text(
    description="Colaborador 3",
    layout=layoutMitad,
    style=styleLabel)

#Lugares
tituloLote = widgets.HTML(
    "<h3 style='color:GREY;'>LOTE DE MUESTREO</h3>")

idLote = widgets.Text(
    description="ID lote",
    placeholder="Ej: LOTE001",
    layout=layoutTercio,
    style=styleLabel)

departamento = widgets.Text(
    description="Departamento",
    placeholder="Ej: Antioquia",
    layout=layoutTercio,
    style=styleLabel)

municipio = widgets.Text(
    description="Municipio",
    placeholder="Municipio",
    layout=layoutTercio,
    style=styleLabel)

tituloRegistro = widgets.HTML("<h3 style='color:GREY;'>REGISTRO FORESTAL</h3>")

#Datos recopilados
nombreComun = widgets.Text(
    description="Nombre común",
    placeholder="Ej: Colibrí o Margarita",
    layout=layoutMitad,
    style=styleLabel)

tipoEspecie = widgets.Dropdown(
    options=[
        ("Pájaro","Pájaro"),
        ("Flor","Flor")],
    description="Especie",
    layout=layoutTercio,
    style=styleLabel)

tipoRegistro = widgets.Dropdown(
    options=[
        ("Migratoria","Migratoria"),
        ("Residente","Residente"),
        ("Invasora","Invasora"),
        ("Silvestre","Silvestre"),
        ("Medicinal","Medicinal"),
        ("Ornamental","Ornamental"),
        ("Desconocido","Desconocido")],
    description="Tipo",
    layout=layoutTercio,
    style=styleLabel)

cantidadIndividuos = widgets.IntText(
    description="Cantidad:",
    layout=layoutTercio,
    style=styleLabel)

#opciones
opciones = widgets.Dropdown(
    options=[
        ("Agregar",1),("Eliminar",2),("Imprimir",3),("Descargar",4)],
    description="Opción",
    layout=layoutTercio,
    style=styleLabel)

tipoDescarga = widgets.Dropdown(
    options=[
        ("Por lotes","lotes"),
        ("Por especies","especies"),("Todo","todo")],
    description="Descargar",
    layout=layoutTercio,
    style=styleLabel)

#Botones
boton = widgets.Button(
    description="Ejecutar",
    button_style="success",
    icon="check")

btnLimpiar = widgets.Button(
    description="Limpiar",
    button_style="warning",
    icon="trash")

salida = widgets.Output()

def ejecutar(b):
    global contadorEspecies
    with salida:
        clear_output()
        opcion = opciones.value

        #Agregar
        if opcion == 1:
            camposVacios = (
                not nombreBrigada.value.strip() or
                not responsableBrigada.value.strip() or
                not idLote.value.strip() or
                not municipio.value.strip() or
                not departamento.value.strip() or
                not nombreComun.value.strip() or
                cantidadIndividuos.value <= 0
            )
            if camposVacios:
                print("Faltan datos por ingresar.")
                return
            nombreClave = nombreComun.value.strip().lower()

            if nombreClave in idsEspecies:
                idRegistro = idsEspecies[nombreClave]
            else:
                prefijo = "PAJ" if tipoEspecie.value == "Pájaro" else "FLO"
                idRegistro = f"{prefijo}-{contadorEspecies:04d}"
                idsEspecies[nombreClave] = idRegistro
                contadorEspecies += 1

            registroForestal.append([
                idRegistro,
                tipoEspecie.value,
                nombreComun.value.strip(),
                tipoRegistro.value,
                cantidadIndividuos.value,
                departamento.value.strip(),
                municipio.value.strip(),
                nombreBrigada.value.strip(),
                idLote.value.strip(),
            ])
            print(f"Registro {idRegistro} agregado — total: {len(registroForestal)}")

          #Eliminar
        elif opcion == 2:
            try:
                indiceEliminar = int(nombreComun.value.strip()) - 1
                if 0 <= indiceEliminar < len(registroForestal):
                    registroForestal.pop(indiceEliminar)
                    print(f"Registro {indiceEliminar + 1} eliminado")
                else:
                    print("Número no válido")

            except:
                print("Ingresa el número del registro en Nombre común")

                #Imprimir
        elif opcion == 3:
            if registroForestal:
                for datos in registroForestal:
                    print(f"\nID: {datos[0]}")
                    print(f"Especie: {datos[1]}")
                    print(f"Nombre común: {datos[2]}")
                    print(f"Tipo: {datos[3]}")
                    print(f"Cantidad: {datos[4]}")
                    print(f"Municipio: {datos[5]}")
                    print(f"Brigada: {datos[6]}")
                    print(f"Lote: {datos[7]}")
            else:
                print("No hay registros guardados")

        #Descargar
        elif opcion == 4:
            if tipoDescarga.value == "lotes":
                lotesRegistrados = []
                for datos in registroForestal:
                    if datos[6] not in lotesRegistrados:
                        lotesRegistrados.append(datos[6])
                        with open(f"lote_{datos[6]}.csv","w",newline="") as archivo:
                            writer = csv.writer(archivo)
                            writer.writerow([
                                "ID",
                                "Especie",
                                "Nombre común",
                                "Tipo",
                                "Cantidad",
                                "Municipio",
                                "Brigada",
                                "Lote"])
                            for fila in registroForestal:
                                if fila[8] == datos[8]:
                                    writer.writerow(fila)
                        files.download(f"lote_{datos[8]}.csv")

        elif opcion == 4:
            if not registroForestal:
                print("Sin registros para exportar.")
                return

            cabecera = ["ID","Especie","Nombre común","Tipo","Cantidad",
                        "Departamento","Municipio","Brigada","Lote"]

            def escribir_y_descargar(nombre_archivo, filas):
                with open(nombre_archivo, "w", newline="", encoding="utf-8-sig") as f:
                    writer = csv.writer(f)
                    writer.writerow(cabecera)
                    writer.writerows(filas)
                files.download(nombre_archivo)
                print(f"Descargado: {nombre_archivo} ({len(filas)} registros)")

            modo = tipoDescarga.value

            if modo == "lotes":
                lotes = sorted({d[8] for d in registroForestal})
                for lote in lotes:
                    filas = [d for d in registroForestal if d[8] == lote]
                    escribir_y_descargar(f"lote_{lote}.csv", filas)

            elif modo == "especies":
                especies = sorted({d[1] for d in registroForestal})
                for esp in especies:
                    filas = [d for d in registroForestal if d[1] == esp]
                    escribir_y_descargar(f"{esp.lower()}.csv", filas)

            elif modo == "todo":
                escribir_y_descargar("inventario_forestal_completo.csv", registroForestal)


def limpiar(b):
    with salida:
        clear_output()

    nombreBrigada.value = ""
    responsableBrigada.value = ""
    colaboradorUno.value     = ""
    colaboradorDos.value     = ""
    colaboradorTres.value    = ""
    idLote.value = ""
    cantidadIndividuos.value= 0
    municipio.value = ""
    nombreComun.value = ""
    departamento.value = ""
    tipoEspecie.value = "Pájaro"
    tipoRegistro.value = "Migratoria"


boton.on_click(ejecutar)
btnLimpiar.on_click(limpiar)

#Presentación
brigadaBox = widgets.VBox([
    tituloBrigada,
    widgets.HBox([nombreBrigada, responsableBrigada]),
    widgets.HBox([colaboradorUno, colaboradorDos, colaboradorTres])])

loteBox = widgets.VBox([
    tituloLote,
    widgets.HBox([idLote, departamento, municipio])])

registroBox = widgets.VBox([
    tituloRegistro,
    widgets.HBox([nombreComun, tipoEspecie, tipoRegistro]),
    widgets.HBox([cantidadIndividuos])])

accionesBox = widgets.VBox([
    widgets.HBox([opciones, tipoDescarga]),
    widgets.HBox([boton, btnLimpiar]),
    salida])

contenedor = widgets.VBox([
    brigadaBox,
    loteBox,
    registroBox,
    accionesBox])

contenedor.layout = widgets.Layout(
    border="solid 2px #444",
    padding="20px",
    width="95%")

display(contenedor)